### ISSUE TITLE
Is paperspace-node supposed to work in-browser?

### ISSUE THREAD

**Issue by TBBle** [Paperspace/paperspace-node#15]
Based on the [Paperspace API docs](https://paperspace.github.io/paperspace-node/)
> JavaScript API client (for Node.js and web browsers)

I expected that using the [paperspace-node](https://www.npmjs.com/package/paperspace-node) module (via [ps_promise](https://www.npmjs.com/package/ps_promise) in my case) would work in a [create-react-app](https://github.com/facebook/create-react-app)-bootstrapped application.

However, I've hit a few problem, and they look suspiciously like assumptions of running on a node.js stack:
* [lib/projectConfig.js] uses `fs.existsSync` which doesn't appear to be available.
* [lib/method.js] uses `readlineSync` only when `global.paperspace_cli` is set, but always imports it.
* [lib/jobs/create.js] uses `archiver` which eventually hits `fs.ReadStream` being missing.

https://github.com/isaacs/node-graceful-fs/issues/121#issuecomment-361884236 suggests that last one might be a bug in [graceful-fs](https://github.com/isaacs/node-graceful-fs), but perhaps it's a problem somewhere else.

Before I sink much more time into trying to fix these things properly, is this even a valid-use case? Is the 'web browsers' mention on the page an oversight, or is there something I need to fix about my environment to make this work?

**Comment by yulianovdey** [comment]
Just in case anyone stumbles upon this, it's very unlikely that this package was actually meant to be used in the browser in its current form. Your Paperspace API key should be kept secret, so be careful not to expose it in a client-side application.

**Comment by dte** [comment]
That is correct. You should not expose your API key and this module is designed for server-side applications.
